import { Employee, Transaction, TransactionType } from '../types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'EMP-101',
    name: 'أحمد سعيد الشيباني',
    jobTitle: 'رئيس قسم المبيعات',
    salary: 5500,
    hireDate: '2024-01-15',
    phone: '777123456',
    notes: 'موظف متميز ومسؤول عن العهد المستديمة',
    isArchived: false,
  },
  {
    id: 'EMP-102',
    name: 'خالد محمد عوض',
    jobTitle: 'محاسب أول',
    salary: 4800,
    hireDate: '2024-05-10',
    phone: '776543210',
    notes: 'يقوم بمهام التدقيق المالي ومطابقة السحب اليومي',
    isArchived: false,
  },
  {
    id: 'EMP-103',
    name: 'فؤاد عبد الله الريمي',
    jobTitle: 'مشرف العلاقات العامة',
    salary: 3500,
    hireDate: '2025-02-01',
    phone: '771987654',
    notes: 'نشيط ومرن في الاستغاثة العاجلة وسلف النقل',
    isArchived: false,
  },
  {
    id: 'EMP-104',
    name: 'سليم يحيى العبسي',
    jobTitle: 'سائق توزيع ومندوب حركات ومشتريات',
    salary: 2800,
    hireDate: '2025-03-20',
    phone: '735111222',
    notes: 'تخصم منه أقساط سلفة المواصلات والسيارة شهرياً',
    isArchived: false,
  },
  {
    id: 'EMP-105',
    name: 'عصام عبد الملك الحميري',
    jobTitle: 'أخصائي دعم تقني وأنظمة معلومات',
    salary: 4000,
    hireDate: '2024-09-01',
    phone: '711222333',
    notes: 'مسؤول المشتريات البرمجية والإنترنت للمؤسسة',
    isArchived: false,
  },
  {
    id: 'EMP-106',
    name: 'جمال يوسف الحاشدي',
    jobTitle: 'حارس مبنى ومشرف لوجستي',
    salary: 2200,
    hireDate: '2025-01-10',
    phone: '700999888',
    notes: 'مؤرشف ومجتهد',
    isArchived: true, // Archived to showcase the archive system
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // احمد سعيد الشيباني (EMP-101)
  {
    id: 'TX-1001',
    employeeId: 'EMP-101',
    date: '2026-05-01',
    type: TransactionType.SALARY,
    statement: 'قيد إثبات راتب شهر مايو الكلي والأساسي',
    debit: 0,
    credit: 5500,
    balance: 5500,
    notes: 'تمت المزامنة بنجاح من الموارد البشرية',
  },
  {
    id: 'TX-1002',
    employeeId: 'EMP-101',
    date: '2026-05-05',
    type: TransactionType.ADVANCE,
    statement: 'سلفة مالية عاجلة لتغطية مصاريف طبية شخصية',
    debit: 800,
    credit: 0,
    balance: 4700,
    notes: 'موافقة المدير التنفيذي',
  },
  {
    id: 'TX-1003',
    employeeId: 'EMP-101',
    date: '2026-05-14',
    type: TransactionType.THURSDAY_ADVANCE,
    statement: 'سلفة الخميس النقدية المعتادة لعطلة نهاية الأسبوع',
    debit: 200,
    credit: 0,
    balance: 4500,
    notes: 'تسليم يدوي للموظف',
  },
  {
    id: 'TX-1004',
    employeeId: 'EMP-101',
    date: '2026-05-25',
    type: TransactionType.BONUS,
    statement: 'مكافأة إضافية لتحقيق تارجت مبيعات الربع الأول',
    debit: 0,
    credit: 600,
    balance: 5100,
    notes: 'معيار الانضباط والإنتاجية',
  },
  {
    id: 'TX-1005',
    employeeId: 'EMP-101',
    date: '2026-05-28',
    type: TransactionType.DEDUCTION,
    statement: 'تأخير غير مبرر في تسليم الفواتير اليومية للمحاسبة',
    debit: 150,
    credit: 0,
    balance: 4950,
    notes: 'إنذار شفهي سابق',
  },

  // خالد محمد عوض (EMP-102)
  {
    id: 'TX-1101',
    employeeId: 'EMP-102',
    date: '2026-05-01',
    type: TransactionType.SALARY,
    statement: 'قيد إثبات راتب شهر مايو الأساسي للمحاسب',
    debit: 0,
    credit: 4800,
    balance: 4800,
  },
  {
    id: 'TX-1102',
    employeeId: 'EMP-102',
    date: '2026-05-10',
    type: TransactionType.ADVANCE,
    statement: 'سلفة مستحقة للموظف الدورية لشراء أثاث مكتبي',
    debit: 500,
    credit: 0,
    balance: 4300,
  },
  {
    id: 'TX-1103',
    employeeId: 'EMP-102',
    date: '2026-05-15',
    type: TransactionType.ABSENCE,
    statement: 'غياب يوم كامل بدون إذن أو عذر مسبق',
    debit: 160,
    credit: 0,
    balance: 4140,
    notes: 'محتسب بنسبة 1/30 من الراتب الأساسي',
  },
  {
    id: 'TX-1104',
    employeeId: 'EMP-102',
    date: '2026-05-18',
    type: TransactionType.CUSTODY,
    statement: 'صرف عهدة مالية مؤقتة للمراجعة والتدقيق الخارجي',
    debit: 1000,
    credit: 0,
    balance: 3140,
    notes: 'تستحق الاسترداد بنهاية المعاملة',
  },
  {
    id: 'TX-1105',
    employeeId: 'EMP-102',
    date: '2026-05-26',
    type: TransactionType.CUSTODY_RETURN,
    statement: 'استرداد العهدة المالية المؤقتة الفائضة بعد انتهاء التدقيق',
    debit: 0,
    credit: 1000,
    balance: 4140,
    notes: 'تمت المطابقة ورفع الأوراق الثبوتية',
  },

  // فؤاد عبد الله الريمي (EMP-103)
  {
    id: 'TX-1201',
    employeeId: 'EMP-103',
    date: '2026-05-01',
    type: TransactionType.SALARY,
    statement: 'راتب شهر مايو الأساسي لمشرف العلاقات العامة',
    debit: 0,
    credit: 3500,
    balance: 3500,
  },
  {
    id: 'TX-1202',
    employeeId: 'EMP-103',
    date: '2026-05-11',
    type: TransactionType.THURSDAY_ADVANCE,
    statement: 'سلفة سريعة لنهاية الأسبوع لتغطية طوارئ عائلية',
    debit: 300,
    credit: 0,
    balance: 3200,
  },
  {
    id: 'TX-1203',
    employeeId: 'EMP-103',
    date: '2026-05-20',
    type: TransactionType.EID_CLOTHES,
    statement: 'مساهمة ملابس العيد والكسوة الموسمية المدعومة',
    debit: 400,
    credit: 0,
    balance: 2800,
  },
  {
    id: 'TX-1204',
    employeeId: 'EMP-103',
    date: '2026-05-28',
    type: TransactionType.TRANSPORT,
    statement: 'بدل مواصلات إضافي لتنفيذ رحلات عمل للجهات الحكومية',
    debit: 0,
    credit: 250,
    balance: 3050,
  },

  // سليم يحيى العبسي (EMP-104)
  {
    id: 'TX-1301',
    employeeId: 'EMP-104',
    date: '2026-05-01',
    type: TransactionType.SALARY,
    statement: 'الراتب الأساسي لشهر مايو للسائق والمشتريات',
    debit: 0,
    credit: 2800,
    balance: 2800,
  },
  {
    id: 'TX-1302',
    employeeId: 'EMP-104',
    date: '2026-05-04',
    type: TransactionType.INSTALLMENT,
    statement: 'سداد قسط شهري دوري مقتطع من ذمة مديونية السيارة',
    debit: 200,
    credit: 0,
    balance: 2600,
  },
  {
    id: 'TX-1303',
    employeeId: 'EMP-104',
    date: '2026-05-14',
    type: TransactionType.THURSDAY_ADVANCE,
    statement: 'سلفة الخميس لتأمين وقود سيارة التوزيع',
    debit: 150,
    credit: 0,
    balance: 2450,
  },
  {
    id: 'TX-1304',
    employeeId: 'EMP-104',
    date: '2026-05-29',
    type: TransactionType.FROZEN_DEBT,
    statement: 'تجميد مديونية سابقة متعثرة لمساعدة الموظف مالياً',
    debit: 0,
    credit: 300,
    balance: 2750,
    notes: 'بأمر من الإدارة لغرض التحفيز والدعم الاجتماعي',
  }
];
